import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "es" }, { lang: "fr" }, { lang: "de" }, { lang: "ru" }, { lang: "pt" }]
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: { icon: "/icon.png" }
};

export default async function RootLayout({
  children, params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: "en" | "es" | "fr" | "de" | "ru" | "pt" }>
}>) {
  return (
    <html lang={(await params).lang}>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
