export const cars = ["classic-car", "modern-car", "van"];

export const places = [
  "havana-airport",
  "varadero-airport",
  "varadero",
  "havana",
  "cayo-coco",
  "cienfuegos",
  "santa-clara",
  "trinidad",
  "vinales",
  "cayo-santa-maria",
  "cayo-guillermo",
];

const transfers = {
  "havana-airport": {
    havana: {
      distance: 23,
      duration: "0:30",
      convertible: 50,
      van: 55,
      "modern-car": 30,
    },
    varadero: {
      distance: 170,
      duration: "2:30",
      convertible: 160,
      van: 180,
      "modern-car": 80,
    },
    vinales: {
      distance: 180,
      duration: "2:30",
      convertible: null,
      van: 190,
      "modern-car": 120,
    },
    cienfuegos: {
      distance: 245,
      duration: "3:00",
      convertible: null,
      van: 220,
      "modern-car": 155,
    },
    "santa-clara": {
      distance: 300,
      duration: "3:30",
      convertible: null,
      van: 285,
      "modern-car": 180,
    },
    trinidad: {
      distance: 330,
      duration: "4:30",
      convertible: null,
      van: 325,
      "modern-car": 250,
    },
    "cayo-santa-maria": {
      distance: 405,
      duration: "5:00",
      convertible: null,
      van: 370,
      "modern-car": 200,
    },
    "cayo-coco": {
      distance: 525,
      duration: "6:30",
      convertible: null,
      van: 540,
      "modern-car": 250,
    },
    "cayo-guillermo": {
      distance: 555,
      duration: "7:00",
      convertible: null,
      van: 515,
      "modern-car": 230,
    },
  },

  "varadero-airport": {
    cardenas: {
      distance: 39,
      duration: "0:40",
      convertible: null,
      van: 60,
      "modern-car": 40,
    },
    havana: {
      distance: 125,
      duration: "2:00",
      convertible: null,
      van: 175,
      "modern-car": 100,
    },
    "havana-airport": {
      distance: 140,
      duration: "2:15",
      convertible: null,
      van: 170,
      "modern-car": 80,
    },
    cienfuegos: {
      distance: 205,
      duration: "2:45",
      convertible: null,
      van: 200,
      "modern-car": 160,
    },
    "santa-clara": {
      distance: 255,
      duration: "3:10",
      convertible: null,
      van: 255,
      "modern-car": 150,
    },
    trinidad: {
      distance: 290,
      duration: "4:00",
      convertible: null,
      van: 325,
      "modern-car": 200,
    },
  },

  havana: {
    "havana-airport": {
      distance: 23,
      duration: "0:30",
      convertible: 50,
      van: 55,
      "modern-car": 30,
    },
    "varadero-airport": {
      distance: 125,
      duration: "2:00",
      convertible: 160,
      van: 175,
      "modern-car": 80,
    }, // La Habana -> Aero Varadero (tabla)
    varadero: {
      distance: 145,
      duration: "2:15",
      convertible: 160,
      van: 180,
      "modern-car": 80,
    },
    vinales: {
      distance: 180,
      duration: "2:30",
      convertible: 180,
      van: 200,
      "modern-car": 130,
    },
    cienfuegos: {
      distance: 240,
      duration: "3:00",
      convertible: null,
      van: 240,
      "modern-car": 155,
    },
    "santa-clara": {
      distance: 300,
      duration: "3:30",
      convertible: null,
      van: 305,
      "modern-car": 200,
    },
    trinidad: {
      distance: 320,
      duration: "4:15",
      convertible: null,
      van: 320,
      "modern-car": 250,
    },
    "cayo-santa-maria": {
      distance: 400,
      duration: "5:00",
      convertible: null,
      van: 350,
      "modern-car": 200,
    },
    "cayo-coco": {
      distance: 525,
      duration: "6:30",
      convertible: null,
      van: 535,
      "modern-car": 250,
    },
    "cayo-guillermo": {
      distance: 550,
      duration: "7:00",
      convertible: null,
      van: 550,
      "modern-car": 230,
    },
  },

  varadero: {
    "varadero-airport": {
      distance: 40,
      duration: "0:45",
      convertible: null,
      van: 75,
      "modern-car": 40,
    },
    havana: {
      distance: 145,
      duration: "2:15",
      convertible: null,
      van: 145,
      "modern-car": 80,
    },
    "havana-airport": {
      distance: 170,
      duration: "2:30",
      convertible: null,
      van: 180,
      "modern-car": 80,
    },
    cienfuegos: {
      distance: 177,
      duration: "2:30",
      convertible: null,
      van: 150,
      "modern-car": 90,
    }, // tabla tiene 177/190 filas; incluyo la 177 como entrada
    cfg_alt: {
      distance: 190,
      duration: "3:00",
      convertible: null,
      van: 205,
      "modern-car": 120,
    }, // segunda fila Cienfuegos (tabla)
    "santa-clara": {
      distance: 240,
      duration: "3:30",
      convertible: null,
      van: 255,
      "modern-car": 150,
    },
    trinidad: {
      distance: 270,
      duration: "4:20",
      convertible: null,
      van: 270,
      "modern-car": 250,
    },
    vinales: {
      distance: 330,
      duration: "4:45",
      convertible: null,
      van: 315,
      "modern-car": 180,
    },
    "cayo-santa-maria": {
      distance: 330,
      duration: "4:30",
      convertible: null,
      van: 250,
      "modern-car": 180,
    },
    "cayo-coco": {
      distance: 465,
      duration: "6:20",
      convertible: null,
      van: 280,
      "modern-car": 200,
    },
  },

  vinales: {
    "havana-airport": {
      distance: 180,
      duration: "2:30",
      convertible: null,
      van: 190,
      "modern-car": 120,
    },
    havana: {
      distance: 180,
      duration: "2:30",
      convertible: 180,
      van: 200,
      "modern-car": 130,
    },
    varadero: {
      distance: 330,
      duration: "4:45",
      convertible: null,
      van: 315,
      "modern-car": 180,
    },
  },

  trinidad: {
    "havana-airport": {
      distance: 330,
      duration: "4:30",
      convertible: null,
      van: 325,
      "modern-car": 250,
    },
    havana: {
      distance: 320,
      duration: "4:15",
      convertible: null,
      van: 320,
      "modern-car": 250,
    },
    varadero: {
      distance: 270,
      duration: "4:20",
      convertible: null,
      van: 270,
      "modern-car": 250,
    },
  },

  "santa-clara": {
    "havana-airport": {
      distance: 300,
      duration: "3:30",
      convertible: null,
      van: 285,
      "modern-car": 180,
    },
    havana: {
      distance: 300,
      duration: "3:30",
      convertible: null,
      van: 305,
      "modern-car": 200,
    },
    varadero: {
      distance: 240,
      duration: "3:30",
      convertible: null,
      van: 255,
      "modern-car": 150,
    },
  },

  cienfuegos: {
    "havana-airport": {
      distance: 245,
      duration: "3:00",
      convertible: null,
      van: 220,
      "modern-car": 155,
    },
    havana: {
      distance: 240,
      duration: "3:00",
      convertible: null,
      van: 240,
      "modern-car": 155,
    },
    varadero: {
      distance: 177,
      duration: "2:30",
      convertible: null,
      van: 150,
      "modern-car": 90,
    },
    var_alt: {
      distance: 190,
      duration: "3:00",
      convertible: null,
      van: 205,
      "modern-car": 120,
    }, // la segunda entrada Cienfuegos desde Varadero
  },

  "cayo-santa-maria": {
    "havana-airport": {
      distance: 405,
      duration: "5:00",
      convertible: null,
      van: 370,
      "modern-car": 200,
    },
    havana: {
      distance: 400,
      duration: "5:00",
      convertible: null,
      van: 350,
      "modern-car": 200,
    },
    varadero: {
      distance: 330,
      duration: "4:30",
      convertible: null,
      van: 250,
      "modern-car": 180,
    },
  },

  "cayo-coco": {
    "havana-airport": {
      distance: 525,
      duration: "6:30",
      convertible: null,
      van: 540,
      "modern-car": 250,
    },
    havana: {
      distance: 525,
      duration: "6:30",
      convertible: null,
      van: 535,
      "modern-car": 250,
    },
    varadero: {
      distance: 465,
      duration: "6:20",
      convertible: null,
      van: 280,
      "modern-car": 200,
    },
  },

  "cayo-guillermo": {
    "havana-airport": {
      distance: 555,
      duration: "7:00",
      convertible: null,
      van: 515,
      "modern-car": 230,
    },
    havana: {
      distance: 550,
      duration: "7:00",
      convertible: null,
      van: 550,
      "modern-car": 230,
    },
  },
};
export const prices = [
  { from: "havana-airport", to: "havana", minivan: 55, classicModern: 30 },
  { from: "havana-airport", to: "varadero", minivan: 180, classicModern: 80 },
  { from: "havana-airport", to: "vinales", minivan: 190, classicModern: 120 },
  {
    from: "havana-airport",
    to: "cienfuegos",
    minivan: 220,
    classicModern: 155,
  },
  {
    from: "havana-airport",
    to: "santa-clara",
    minivan: 285,
    classicModern: 180,
  },
  { from: "havana-airport", to: "trinidad", minivan: 325, classicModern: 250 },
  {
    from: "havana-airport",
    to: "cayo-santa-maria",
    minivan: 370,
    classicModern: 200,
  },
  { from: "havana-airport", to: "cayo-coco", minivan: 540, classicModern: 250 },
  {
    from: "havana-airport",
    to: "cayo-guillermo",
    minivan: 515,
    classicModern: 230,
  },
  {
    from: "varadero-airport",
    to: "havana-airport",
    minivan: 170,
    classicModern: 80,
  },
  {
    from: "varadero-airport",
    to: "cienfuegos",
    minivan: 200,
    classicModern: 160,
  },
  { from: "varadero-airport", to: "havana", minivan: 175, classicModern: 100 },
  {
    from: "varadero-airport",
    to: "santa-clara",
    minivan: 255,
    classicModern: 150,
  },
  {
    from: "varadero-airport",
    to: "trinidad",
    minivan: 325,
    classicModern: 200,
  },
  { from: "varadero-airport", to: "varadero", minivan: 60, classicModern: 40 },
  { from: "havana", to: "havana-airport", minivan: 55, classicModern: 30 },
  { from: "havana", to: "varadero", minivan: 180, classicModern: 80 },
  { from: "havana", to: "cayo-coco", minivan: 535, classicModern: 250 },
  { from: "havana", to: "cayo-guillermo", minivan: 550, classicModern: 230 },
  { from: "havana", to: "cayo-santa-maria", minivan: 350, classicModern: 200 },
  { from: "havana", to: "cienfuegos", minivan: 240, classicModern: 155 },
  { from: "havana", to: "santa-clara", minivan: 305, classicModern: 200 },
  { from: "havana", to: "trinidad", minivan: 320, classicModern: 250 },
  { from: "havana", to: "vinales", minivan: 200, classicModern: 130 },
  { from: "varadero", to: "havana-airport", minivan: 180, classicModern: 80 },
  { from: "varadero", to: "varadero-airport", minivan: 75, classicModern: 40 },
  { from: "varadero", to: "cienfuegos", minivan: 150, classicModern: 90 },
  { from: "varadero", to: "havana", minivan: 145, classicModern: 80 },
  { from: "varadero", to: "santa-clara", minivan: 255, classicModern: 150 },
  { from: "varadero", to: "trinidad", minivan: 270, classicModern: 250 },
  { from: "varadero", to: "vinales", minivan: 315, classicModern: 180 },
];
export const LABELS = {
  en: {
    "havana-airport": "Havana Airport (HAV)",
    "varadero-airport": "Varadero Airport (VRA)",
    havana: "Havana",
    varadero: "Varadero",
    vinales: "Viñales",
    cienfuegos: "Cienfuegos",
    "santa-clara": "Santa Clara",
    trinidad: "Trinidad",
    "cayo-santa-maria": "Cayo Santa Maria",
    "cayo-coco": "Cayo Coco",
    "cayo-guillermo": "Cayo Guillermo",
  },
  es: {
    "havana-airport": "Aeropuerto de La Habana (HAV)",
    "varadero-airport": "Aeropuerto de Varadero (VRA)",
    havana: "La Habana",
    varadero: "Varadero",
    vinales: "Viñales",
    cienfuegos: "Cienfuegos",
    "santa-clara": "Santa Clara",
    trinidad: "Trinidad",
    "cayo-santa-maria": "Cayo Santa María",
    "cayo-coco": "Cayo Coco",
    "cayo-guillermo": "Cayo Guillermo",
  },
  pt: {
    "havana-airport": "Aeroporto de Havana (HAV)",
    "varadero-airport": "Aeroporto de Varadero (VRA)",
    havana: "Havana",
    varadero: "Varadero",
    vinales: "Viñales",
    cienfuegos: "Cienfuegos",
    "santa-clara": "Santa Clara",
    trinidad: "Trinidad",
    "cayo-santa-maria": "Cayo Santa Maria",
    "cayo-coco": "Cayo Coco",
    "cayo-guillermo": "Cayo Guillermo",
  },
  fr: {
    "havana-airport": "Aéroport de La Havane (HAV)",
    "varadero-airport": "Aéroport de Varadero (VRA)",
    havana: "La Havane",
    varadero: "Varadero",
    vinales: "Viñales",
    cienfuegos: "Cienfuegos",
    "santa-clara": "Sainte Claire",
    trinidad: "Trinidad",
    "cayo-santa-maria": "Cayo Santa Maria",
    "cayo-coco": "Cayo Coco",
    "cayo-guillermo": "Cayo Guillermo",
  },
  de: {
    "havana-airport": "Flughafen Havanna (HAV)",
    "varadero-airport": "Flughafen Varadero (VRA)",
    havana: "Havanna",
    varadero: "Varadero",
    vinales: "Viñales",
    cienfuegos: "Cienfuegos",
    "santa-clara": "Santa Clara",
    trinidad: "Trinidad",
    "cayo-santa-maria": "Cayo Santa Maria",
    "cayo-coco": "Cayo Coco",
    "cayo-guillermo": "Cayo Guillermo",
  },
  ru: {
    "havana-airport": "Аэропорт Гаваны (HAV)",
    "varadero-airport": "Аэропорт Варадеро (VRA)",
    havana: "Гавана",
    varadero: "Варадеро",
    vinales: "Виньялес",
    cienfuegos: "Сьенфуэгос",
    "santa-clara": "Санта-Клара",
    trinidad: "Тринидад",
    "cayo-santa-maria": "Кайо Санта-Мария",
    "cayo-coco": "Кайо Коко",
    "cayo-guillermo": "Кайо Гильермо",
  },
};
